# Generated by Django 3.2.7 on 2021-12-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
